import { StyleSheet } from "react-native";
import { colors, fontSize, radius, spacing, tint } from "@/theme/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, padding: spacing.xxl },
  duelContent: { gap: spacing.md, paddingBottom: spacing.massive },
  title: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: "800" },
  sub: { color: colors.textSecondary, marginTop: spacing.sm },
  subRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs, marginTop: spacing.sm },
  subRowLabel: { marginTop: 0 },
  card: { marginTop: spacing.xl, backgroundColor: colors.card, borderRadius: radius.card, borderColor: colors.border, borderWidth: 1, padding: spacing.lg },
  cardTitle: { color: colors.textPrimary, fontWeight: "700", fontSize: fontSize.md, marginTop: spacing.lg },
  matchBtn: { marginTop: spacing.xxl, backgroundColor: colors.duel, borderRadius: radius.button, padding: spacing.lg, alignItems: "center" },
  matchLabel: { color: colors.textPrimary, fontWeight: "800" },
  secondaryBtn: { marginTop: spacing.xl, borderRadius: radius.button, borderWidth: 1, borderColor: colors.border, padding: spacing.md, alignItems: "center" },
  secondaryLabel: { color: colors.textPrimary },
  searching: { color: colors.duel, fontWeight: "800", fontSize: fontSize.lg },
  matchOppRow: { flexDirection: "row", alignItems: "center", marginTop: spacing.xl, gap: spacing.md, flexWrap: "wrap" },
  vsInline: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: "800", flex: 1, flexShrink: 1 },
  matchOppAvatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.surface },
  matchOppInitial: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  matchOppInitialTxt: { color: colors.textPrimary, fontWeight: "800", fontSize: fontSize.lg },
  scoreCellStart: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.xs },
  scoreCellEnd: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: spacing.xs },
  scoreName: { flexShrink: 1 },
  duelMiniAvatar: { width: 26, height: 26, borderRadius: 13, backgroundColor: colors.surface },
  duelMiniInitial: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  duelMiniInitialTxt: { color: colors.textPrimary, fontWeight: "800", fontSize: fontSize.xs },
  scoreRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginBottom: spacing.sm },
  score: { color: colors.textPrimary, fontWeight: "800" },
  option: { padding: spacing.md, borderRadius: radius.button, borderWidth: 1, borderColor: colors.border, marginTop: spacing.sm },
  optionSelected: { borderColor: colors.duel, backgroundColor: tint.duel },
  optionLabel: { color: colors.textPrimary, flexShrink: 1, lineHeight: 20 },
  correct: { borderColor: colors.success, backgroundColor: tint.success },
  wrong: { borderColor: colors.danger, backgroundColor: tint.danger },
  overlay: {
    position: "absolute",
    left: spacing.xxl,
    right: spacing.xxl,
    top: "40%",
    backgroundColor: "rgba(13,13,13,0.95)",
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    alignItems: "center",
  },
  overlayTitle: { color: colors.textPrimary, fontWeight: "800", fontSize: fontSize.md },
  overlayText: { color: colors.textSecondary, marginTop: spacing.sm },
  codeWrap: { maxHeight: 220 },
  replayRow: { marginTop: spacing.md },
  replayTrack: {
    height: 10,
    borderRadius: radius.pill,
    overflow: "hidden",
    backgroundColor: colors.surface,
    marginTop: spacing.sm,
    flexDirection: "row",
  },
  replayBarMine: { height: 10, backgroundColor: colors.success },
  replayBarOpp: { height: 10, backgroundColor: colors.duel },
});
