import { StyleSheet } from "react-native";
import { colors, font, fontSize, glow, radius, spacing, tint } from "@/theme/theme";

export const styles = StyleSheet.create({
  arenaContainer: { flex: 1, backgroundColor: colors.background },
  screenBody: { flex: 1, padding: spacing.xxl, overflow: "hidden" },
  list: { flex: 1 },
  duelContent: { padding: spacing.xxl, paddingBottom: spacing.massive, gap: spacing.md },
  title: { color: colors.textPrimary, fontFamily: font.mono, fontSize: fontSize.xl, fontWeight: "800" },
  sub: { color: colors.textSecondary, marginTop: spacing.sm },
  subRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs, marginTop: spacing.sm },
  subRowLabel: { marginTop: 0 },
  card: { backgroundColor: colors.card, borderRadius: radius.card, borderColor: colors.border, borderWidth: 1, padding: spacing.xl },
  cardTitle: { color: colors.textPrimary, fontWeight: "700", fontSize: fontSize.md },
  matchBtn: { marginTop: spacing.xl, backgroundColor: colors.duel, borderRadius: radius.button, padding: spacing.lg, alignItems: "center", justifyContent: "center", ...glow.duel },
  matchLabel: { color: colors.textPrimary, fontWeight: "800" },
  secondaryBtn: { marginTop: spacing.xl, borderRadius: radius.button, borderWidth: 1, borderColor: colors.border, padding: spacing.md, alignItems: "center", justifyContent: "center", minHeight: 48 },
  secondaryLabel: { color: colors.textPrimary },
  searching: { color: colors.duel, fontFamily: font.mono, fontWeight: "800", fontSize: fontSize.lg },
  matchOppRow: { flexDirection: "row", alignItems: "center", marginTop: spacing.xl, gap: spacing.md },
  vsInline: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: "800", flex: 1, flexShrink: 1 },
  matchOppAvatar: { width: spacing.giant, height: spacing.giant, borderRadius: spacing.xxl, backgroundColor: colors.surface },
  matchOppInitial: {
    width: spacing.giant,
    height: spacing.giant,
    borderRadius: spacing.xxl,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  matchOppInitialTxt: { color: colors.textPrimary, fontWeight: "800", fontSize: fontSize.lg },
  scoreCellStart: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.xs },
  scoreCellEnd: { flex: 1, flexDirection: "row-reverse", alignItems: "center", justifyContent: "flex-start", gap: spacing.xs },
  scoreName: { flexShrink: 1 },
  duelMiniAvatar: { width: spacing.xxl, height: spacing.xxl, borderRadius: spacing.md, backgroundColor: colors.surface },
  duelMiniInitial: {
    width: spacing.xxl,
    height: spacing.xxl,
    borderRadius: spacing.md,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  duelMiniInitialTxt: { color: colors.textPrimary, fontWeight: "800", fontSize: fontSize.xs },
  scoreRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  score: { color: colors.textPrimary, fontFamily: font.mono, fontWeight: "800", fontVariant: ["tabular-nums"] },
  option: { padding: spacing.md, borderRadius: radius.button, borderWidth: 1, borderColor: colors.border, marginTop: spacing.sm, minHeight: 44, justifyContent: "center" },
  optionSelected: { borderColor: colors.duel, backgroundColor: tint.duel },
  optionLabel: { color: colors.textPrimary, flexShrink: 1, lineHeight: 20 },
  correct: { borderColor: colors.success, backgroundColor: tint.success },
  wrong: { borderColor: colors.danger, backgroundColor: tint.danger },
  overlay: {
    position: "absolute",
    left: spacing.xxl,
    right: spacing.xxl,
    top: "40%",
    backgroundColor: "rgba(13,13,13,0.95)",
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    alignItems: "center",
    maxHeight: "50%",
  },
  overlayTitle: { color: colors.textPrimary, fontFamily: font.mono, fontWeight: "800", fontSize: fontSize.md },
  overlayConnection: { top: "20%" },
  overlayText: { color: colors.textSecondary, marginTop: spacing.sm },
  replayCard: { marginTop: spacing.xl },
  replayRow: { marginTop: spacing.md },
  replayTrack: {
    height: 10,
    borderRadius: radius.pill,
    overflow: "hidden",
    backgroundColor: colors.surface,
    marginTop: spacing.sm,
    flexDirection: "row",
  },
  replayBarMine: { height: "100%", backgroundColor: colors.success },
  replayBarOpp: { height: "100%", backgroundColor: colors.duel },
});
