import { StyleSheet } from "react-native";
import { colors, font, fontSize, glow, radius, spacing } from "@/theme/theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  guestContainer: { flex: 1, backgroundColor: colors.background },
  guestMain: { flex: 1, justifyContent: "center", padding: spacing.xxl, gap: spacing.lg },
  guestHero: { alignItems: "center", overflow: "hidden" },
  guestName: { marginTop: spacing.md, color: colors.textPrimary, fontFamily: font.mono, fontSize: fontSize.lg, fontWeight: "800" },
  guestEmail: { color: colors.textSecondary, marginTop: spacing.xs, textAlign: "center" },
  guestMeta: { color: colors.success, fontFamily: font.mono, marginTop: spacing.sm, fontWeight: "700" },
  guestShield: { color: colors.textSecondary, fontSize: fontSize.sm },
  guestField: { color: colors.textSecondary, marginTop: spacing.md, marginBottom: spacing.sm, fontWeight: "700" },
  guestRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  guestChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.background,
  },
  guestChipOn: { borderColor: colors.accent, backgroundColor: colors.card },
  guestChipText: { color: colors.textSecondary, fontWeight: "700" },
  guestChipTextOn: { color: colors.accent },
  guestBtn: {
    marginTop: spacing.lg,
    backgroundColor: colors.accent,
    borderRadius: radius.button,
    paddingVertical: spacing.md,
    alignItems: "center",
    ...glow.accent,
  },
  guestBtnLbl: { color: colors.onAccent, fontWeight: "800" },
  guestDangerCard: { borderColor: colors.danger },
  guestDangerRow: { flexDirection: "row" as const, justifyContent: "space-between" as const, alignItems: "center" as const, minHeight: 44, borderWidth: 1, borderColor: colors.border, borderRadius: radius.button, paddingHorizontal: spacing.md },
  guestDangerRowPress: { opacity: 0.75 },
  guestDangerLeft: { flexDirection: "row" as const, alignItems: "center" as const, gap: spacing.sm },
  guestDangerLbl: { color: colors.danger, fontWeight: "700" as const },
  guestChev: { color: colors.textSecondary, fontSize: fontSize.lg },
});
