import { StyleSheet } from "react-native";
import { colors, font, fontSize, glow, radius, spacing, tint } from "@/theme/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scroll: { flex: 1 },
  content: { flexGrow: 1, paddingBottom: spacing.lg },
  heroZone: {
    paddingHorizontal: spacing.xxl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    overflow: "hidden",
  },
  date: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1, textTransform: "lowercase" },
  greeting: { color: colors.textPrimary, fontFamily: font.mono, fontSize: fontSize.lg, fontWeight: "800", marginTop: spacing.md },
  body: { paddingHorizontal: spacing.xxl, paddingTop: spacing.xxl },
  todayPanel: { marginBottom: spacing.xxl },
  statRow: { flexDirection: "row", gap: spacing.xl },
  statCell: { flex: 1, gap: spacing.sm },
  statDivider: { width: 1, backgroundColor: colors.border },
  statValueRow: { flexDirection: "row", alignItems: "flex-end" },
  statValue: { color: colors.textPrimary, fontFamily: font.mono, fontSize: fontSize.xl, fontWeight: "800", fontVariant: ["tabular-nums"] },
  statUnit: { color: colors.textSecondary, fontFamily: font.mono, fontSize: fontSize.sm, fontWeight: "600" },
  statLabel: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
  streakRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  dotRow: { flexDirection: "row", gap: spacing.xs },
  dot: { width: spacing.md, height: spacing.xs, borderRadius: 2, backgroundColor: colors.textMuted },
  dotDone: { backgroundColor: colors.accent },
  levelRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginTop: spacing.xl, paddingTop: spacing.xl, borderTopWidth: 1, borderTopColor: colors.border },
  levelChip: { color: colors.accent, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
  levelBar: { flex: 1, minWidth: spacing.massive },
  levelXp: { color: colors.textSecondary, fontFamily: font.mono, fontSize: fontSize.xs, fontVariant: ["tabular-nums"], flexShrink: 1 },
  hero: { backgroundColor: colors.accent, borderRadius: radius.card, padding: spacing.xxl, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.xxl, ...glow.accent },
  heroText: { flex: 1, marginRight: spacing.md },
  heroTitle: { color: colors.onAccent, fontSize: fontSize.lg, fontWeight: "800" },
  heroSub: { color: colors.onAccent, opacity: 0.65, marginTop: spacing.xs, fontWeight: "600", fontSize: fontSize.sm },
  tileRow: { flexDirection: "row", gap: spacing.lg },
  tile: { flex: 1 },
  tileFrame: { gap: spacing.sm },
  tileDuel: { borderColor: colors.duel, backgroundColor: tint.duel },
  tileTitle: { color: colors.textPrimary, fontWeight: "700", fontSize: fontSize.base },
  tileSub: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
  logWrap: { flex: 1, marginTop: spacing.xxl },
  logZone: {
    flexGrow: 1,
    minHeight: 170,
    paddingHorizontal: spacing.xxl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: spacing.sm,
    overflow: "hidden",
  },
  logTitle: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
  logLine: { color: colors.textSecondary, fontFamily: font.mono, fontSize: fontSize.sm, fontVariant: ["tabular-nums"] },
});
