import { StyleSheet } from "react-native";
import { colors, font, fontSize, radius, spacing, tint } from "@/theme/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.xxl, paddingBottom: spacing.massive },
  date: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1, textTransform: "lowercase" },
  greeting: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: "800", marginTop: spacing.sm, marginBottom: spacing.xxl },
  todayPanel: { backgroundColor: colors.card, borderRadius: radius.card, borderWidth: 1, borderColor: colors.border, padding: spacing.xl, marginBottom: spacing.xxxl },
  statRow: { flexDirection: "row", gap: spacing.xl },
  statCell: { flex: 1, gap: spacing.sm },
  statDivider: { width: 1, backgroundColor: colors.border },
  statValueRow: { flexDirection: "row", alignItems: "baseline" },
  statValue: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: "800", fontVariant: ["tabular-nums"] },
  statUnit: { color: colors.textSecondary, fontSize: fontSize.sm, fontWeight: "600" },
  statLabel: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
  streakRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  dotRow: { flexDirection: "row", gap: spacing.xs, marginTop: spacing.xs },
  dot: { width: 12, height: 4, borderRadius: 2, backgroundColor: colors.textMuted },
  dotDone: { backgroundColor: colors.accent },
  levelRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginTop: spacing.xl, paddingTop: spacing.xl, borderTopWidth: 1, borderTopColor: colors.border },
  levelChip: { color: colors.accent, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
  levelBar: { flex: 1 },
  levelXp: { color: colors.textSecondary, fontFamily: font.mono, fontSize: fontSize.xs, fontVariant: ["tabular-nums"] },
  hero: { backgroundColor: colors.accent, borderRadius: radius.card, padding: spacing.xl, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.lg },
  heroTitle: { color: colors.onAccent, fontSize: fontSize.lg, fontWeight: "800" },
  heroSub: { color: colors.onAccent, opacity: 0.65, marginTop: 2, fontWeight: "600", fontSize: fontSize.sm },
  tileRow: { flexDirection: "row", gap: spacing.lg },
  tile: { flex: 1, backgroundColor: colors.card, borderRadius: radius.card, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, gap: spacing.xs },
  tileDuel: { borderColor: colors.duel, backgroundColor: tint.duel },
  tileTitle: { color: colors.textPrimary, fontWeight: "700", fontSize: fontSize.base, marginTop: spacing.sm },
  tileSub: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.xs, letterSpacing: 1 },
});
