import { StyleSheet } from "react-native";
import { colors, font, fontSize, glow, radius, spacing } from "@/theme/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scroll: { flex: 1 },
  loadingInner: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: spacing.xxl },
  scrollInner: { flexGrow: 1, padding: spacing.xxl, paddingTop: spacing.giant, gap: spacing.lg },
  title: { color: colors.textPrimary, fontFamily: font.mono, fontSize: fontSize.xl, fontWeight: "800" },
  counter: { color: colors.textMuted, fontFamily: font.mono, fontSize: fontSize.sm, fontVariant: ["tabular-nums"] },
  prompt: { color: colors.textSecondary, fontSize: fontSize.md, lineHeight: 28 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.button,
    backgroundColor: colors.card,
    color: colors.textPrimary,
    minHeight: 54,
    paddingHorizontal: spacing.lg,
    fontSize: fontSize.base,
    fontFamily: font.mono,
  },
  navRow: { flexDirection: "row", gap: spacing.sm },
  navButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: radius.button,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  navButtonDisabled: { opacity: 0.35 },
  navLabel: { color: colors.textPrimary, fontWeight: "600", fontSize: fontSize.sm },
  submitButton: {
    minHeight: 52,
    borderRadius: radius.button,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.md,
    ...glow.accent,
  },
  submitLabel: { color: colors.onAccent, fontWeight: "800", fontSize: fontSize.md },
  message: { color: colors.textSecondary, fontSize: fontSize.md, lineHeight: 24 },
  footerSpacer: { flex: 1 },
  showAnswerBtn: {
    minHeight: 48,
    borderRadius: radius.button,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.xs,
  },
  showAnswerLabel: { color: colors.textPrimary, fontWeight: "700", fontSize: fontSize.sm },
  refHeading: { color: colors.textMuted, fontSize: fontSize.sm, fontWeight: "700", marginTop: spacing.sm },
  refBody: {
    marginTop: spacing.xs,
    color: colors.textSecondary,
    fontSize: fontSize.md,
    lineHeight: 24,
    fontFamily: font.mono,
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: radius.button,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryLabel: { color: colors.textPrimary, fontWeight: "700" },
});
